// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpx01EJy3jbKXtoyEzAnuAmKfWNwkQK48',
    appId: '1:786340999899:web:b86497e9d50fdc425152fe',
    messagingSenderId: '786340999899',
    projectId: 'club-659c7',
    authDomain: 'club-659c7.firebaseapp.com',
    storageBucket: 'club-659c7.firebasestorage.app',
    measurementId: 'G-0KTM3S5EGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWDUEYI1wW0fENexMGcNizz0QGmwuQy4',
    appId: '1:786340999899:android:5f9c45015f3d67f05152fe',
    messagingSenderId: '786340999899',
    projectId: 'club-659c7',
    storageBucket: 'club-659c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-zFYWwM1_w-4C-8cI6EZ-Al-joZoXeBQ',
    appId: '1:786340999899:ios:6c13c7dfbac36ba25152fe',
    messagingSenderId: '786340999899',
    projectId: 'club-659c7',
    storageBucket: 'club-659c7.firebasestorage.app',
    iosBundleId: 'com.example.club',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-zFYWwM1_w-4C-8cI6EZ-Al-joZoXeBQ',
    appId: '1:786340999899:ios:6c13c7dfbac36ba25152fe',
    messagingSenderId: '786340999899',
    projectId: 'club-659c7',
    storageBucket: 'club-659c7.firebasestorage.app',
    iosBundleId: 'com.example.club',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpx01EJy3jbKXtoyEzAnuAmKfWNwkQK48',
    appId: '1:786340999899:web:ca1640ce36ab7df95152fe',
    messagingSenderId: '786340999899',
    projectId: 'club-659c7',
    authDomain: 'club-659c7.firebaseapp.com',
    storageBucket: 'club-659c7.firebasestorage.app',
    measurementId: 'G-NJ1ZXDM3MM',
  );
}
